### PR TITLE
Replaced lighty with gunicorn.

### PR DESCRIPTION
**Pull request by radeusgd**

### CODE REVIEW

**Comment by psenchanka** [comment]
Looks good, but don't forget to merge latest `develop` and clean up the code from lighty references (some of imports are named `lighttpd_main`).

**Comment by psenchanka** [comment]
Also, here is the link we've discussed before: http://docs.gunicorn.org/en/stable/deploy.html#deploying-gunicorn (also https://serverfault.com/a/331263).
TL;DR: without nginx the setup is vulnerable to very simple DoS.
@accek, do you think it's a problem? We have no security measures in filetracker anyway, so...

**Comment by psenchanka** [comment]
LGTM.

**Comment by accek** [comment]
> TL;DR: without nginx the setup is vulnerable to very simple DoS.
> @accek, do you think it's a problem? We have no security measures in filetracker anyway, so...

I don't think this is an issue here, as we already assume filetracker is run in an isolated network in a few other places.

**Pull request merged**
